[comit] Forward Email?
YunoHost-Apps/nextcloud_ynh pull request #753
Opened 2024-11-17 11:54 UTC by Thatoo

## Problem

Be able to choose to use LDAP forward emails from LDAP as nextcloud users' email instead of main ynh LDAP emails.

## Solution

Add an option in config panel that change mail to maildrop in nextcloud LDAP setting and change $install_dir/apps/user_ldap/lib/User/User.php to retrieve the second value from the LDAP maildrop array as discuss in here : https://forum.yunohost.org/t/adresses-de-transfert-dans-ldap/31856

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2024-11-17 12:34 UTC, rodinux commented
!testme

2024-11-17 12:43 UTC, ericgaspar requested changes

2024-11-17 12:43 UTC, ericgaspar commented on config_panel.toml
> +    name.fr = "Emails de transfert?"
```suggestion
    name.fr = "E-mails de transfert?"
```

2024-11-17 12:43 UTC, ericgaspar commented on config_panel.toml
> +        ask.en = "Set yunohost user's forward email instead of yunohost user's main email?"
```suggestion
        ask.en = "Set YunoHost user's forward email instead of YunoHost user's main email?"
```

2024-11-17 12:43 UTC, ericgaspar commented on config_panel.toml
> +        ask.fr = "Utiliser les emails de transfert des utilisateurs de yunohost plutôt que les emails principaux ?"
```suggestion
        ask.fr = "Utiliser les e-mails de transfert des utilisateurs de YunoHost plutôt que les e-mails principaux ?"
```

2024-11-17 12:43 UTC, ericgaspar commented on config_panel.toml
> +        help.en = "If all your users have set a forward email and aren't using yunohost emails, you may choose to set their forward email as their nextcloud email setting."
```suggestion
        help.en = "If all your users have set a forward email and aren't using YunoHost emails, you may choose to set their forward email as their Nextcloud email setting."
```

2024-11-17 12:43 UTC, ericgaspar commented on config_panel.toml
> +        help.fr = "Si tous vos utilisateurs ont paramétré un email de transfert et n'utilise pas du tout les emails de leur compte yunohost, vous pouvez paramétrer nextcloud d'utiliser les emails de
```suggestion
        help.fr = "Si tous vos utilisateurs ont paramétré un e-mail de transfert et n'utilise pas du tout les e-mails de leur compte YunoHost, vous pouvez paramétrer Nextcloud d'utiliser les e-mails de transfert."
```

2024-11-17 12:43 UTC, ericgaspar commented on config_panel.toml
> +    name.fr = "Emails de transfert?"
```suggestion
    name.fr = "E-mails de transfert?"
```

2024-11-17 12:59 UTC, Thatoo commented
thank you @ericgaspar for these suggestions.

2024-11-17 20:36 UTC, alexAubin commented
(smol poke @zamentur because this may be interesting for you idk)

2024-11-19 16:43 UTC, rodinux commented
Hello, could we rerun the tests CI ?

2024-11-21 15:05 UTC, Thatoo commented
!testme

2024-11-23 00:02 UTC, Thatoo commented
Could someone explain me why the test has failed?

2024-11-27 08:30 UTC, zamentur commented
Timeout... The test has made more than 7h.

2024-11-27 12:59 UTC, ericgaspar commented
relaunching the test will just relaunch the time out issue 😬

2024-11-27 13:59 UTC, Thatoo commented
Then, what can be done?

2024-11-27 14:20 UTC, zamentur commented
3 ways are possible:
- Reduce the number of tests
- Increase the timeout
- Increase the speed of the test

2024-11-27 14:22 UTC, Thatoo commented
Ok, so it isn't in my hand except I should not launch a new test when plenty of others are already on the go.
How can I know when it's suitable to start a test?

2024-11-27 14:34 UTC, Thatoo commented
Thank you @ericgaspar

2024-11-27 19:18 UTC, rodinux commented
Again, as last night the links for 29.0.9 release have disappear...

2024-12-01 23:16 UTC, Thatoo commented
I should check if on a fresh install of ynh 12 with nc, the LDAP config name is empty, "" or if it's `s01`. For some reason when I did my test, the LDAP config NC was using didn't have any name, that's why I wrote with "" but when I read https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#ldap-commands, it should be `s01`.

2024-12-03 20:55 UTC, alexAubin approved these changes

2024-12-03 20:55 UTC, alexAubin commented on scripts/config
> +    if [ $(echo $ldapEmail | grep -Po "maildrop") = "maildrop" ]
```suggestion
    if [ "$(echo $ldapEmail | grep -Po "maildrop")" = "maildrop" ]
```

2024-12-03 21:03 UTC, merged

2024-12-05 13:30 UTC, Thatoo commented
They have accepted my PR upstream https://github.com/nextcloud/server/pull/49404/files so when Nextcloud 31 will be in testing, it would require, I believe (test will be needed) to simplify `set__enable_forward_email()` to

```
set__enable_forward_email() {
    if [ "$enable_forward_email" -eq "0" ]; then
        exec_occ ldap:set-config "" ldapEmailAttribute "mail"
    elif [ "$enable_forward_email" -eq "1" ]; then
        exec_occ ldap:set-config "" ldapEmailAttribute "maildrop"
    fi
    ynh_app_setting_set --app=$app --key=enable_forward_email --value="$enable_forward_email"
}
```